### ISSUE TITLE
《使用webpack 定制前端开发环境》这本书内容空白

### ISSUE THREAD

**Issue by ChloeKurumi** [lm-rebooter/NuggetsBooklet#7]

**Comment by lm-rebooter** [comment]
![image](https://github.com/user-attachments/assets/6c9b69b6-5d00-4c56-8056-6a12f4766bf5)

里面是有内容的，刷新下再看看

**Comment by ChloeKurumi** [comment]
> ![image](https://private-user-images.githubusercontent.com/26397610/382617931-6c9b69b6-5d00-4c56-8056-6a12f4766bf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTUxNTUsIm5iZiI6MTczMDY5NDg1NSwicGF0aCI6Ii8yNjM5NzYxMC8zODI2MTc5MzEtNmM5YjY5YjYtNWQwMC00YzU2LTgwNTYtNmExMmY0NzY2YmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA0MzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYTBkMTJjNmJmMzVlY2RkYWI0NWMxMmJkZjAxZTdiMDI5Y2NjNTVhNGZlNWE1ZmE0MzIzOWFmZDE4MDkzNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G96KweAKBy0qAOlQNU4NbplDJ3ZsdyDwUTTbBCK_N20)
> 
> 里面是有内容的，刷新下再看看

你看里面内容啊！！没东西，git下来都是0kb

**Comment by lm-rebooter** [comment]
回头我找找 维护一下

**Comment by ChloeKurumi** [comment]
> 回头我找找 维护一下

大佬，ai练，掘金免费领小册领了嘛？
